# explicit commands for building the site
# and the folder to publish
[build]
command = "npm run generate"
publish = "dist"

[build.environment]
# cache Cypress binary in local "node_modules" folder
# so Netlify caches it
CYPRESS_CACHE_FOLDER = "./node_modules/CypressBinary"
# set TERM variable for terminal output
TERM = "xterm"

[[plugins]]
# local Cypress plugin will test our site after it is built
package = "netlify-plugin-cypress"
  [plugins.inputs]
    # skip testing local site before deploy
    skip = true
    record = true
  [plugins.inputs.onSuccess]
    # run E2E tests against the deployed URL
    enable = true
    record = true
    group = 'deployed'
